### ISSUE TITLE
Add hooks implementation for React Loads

### ISSUE THREAD

**Issue by jxom** [jxom/react-loads#15]
It would be nice to add the new React Hooks feature into React Loads. It is quite easy with the current implementation of React Loads (using the render props pattern) to nest `<Loads>`, which creates a 'fake hierarchy' which becomes hard to read and understand. 

A simple usage of the React Loads hook implementation would be something like:

```jsx
export default () => {
  const getRandomDog = () => axios.get('https://dog.ceo/api/breeds/image/random');
  const { load, response, error, states } = useLoads({ load: getRandomDog });
  return (
    <Fragment>
        {states.isIdle && <button onClick={load}>Load random dog</button>}
        {states.isLoading && <div>Loading...</div>}
        {states.isSuccess && <img src={response.data.message} alt="Dog" />}
        {states.isError && <div>An error occurred! {error.message}</div>}
        {(states.isSuccess || states.isError) && <button onClick={load}>Load another dog</button>}
    </Fragment>
  );
}
```

**Comment by jxom** [comment]
Hey @benneq,

I was thinking about your use case. I think it might be nice to specify an `inputs` parameter to `useLoads`. Whenever one of the `inputs` values change, then it will invoke the loading function again. In this case, you can see it is being used in the update todo `useLoads`. Thoughts?

```jsx
export default function Todo(props) {
  const { id } = props;

  const getTodoById = id => ...;
  const getTodoByIdLoader = useLoads(getTodoById, { loadOnMount: true });

  const updateTodoById = () => ...; // use getTodoByIdLoader.response.id here
  const updateTodoByIdLoader = useLoads(updateTodoById, {}, [getTodoByIdLoader.response.id]);

  return ...
}
```

**Comment by benneq** [comment]
@jxom Thanks for your response and ideas!

I've written my own `useAsync` hook as a proof of concept. (It's lacking several features of Loads - I just wanted to figure out what's the best way in terms of usability). It kinda works, but I'm not 100% satisfied.

Btw: I did **not** include `loadOnMount`, because you can get the same behavior using `useEffect`, which is much more flexible. (For example, you can simply reload on route params change.)

Here's how I currently use it:
```ts
const getTodoById = (id: string) => axios.get(`http://.../${id}`);
const { response: todo, load: loadTodo } = useAsync(getTodoById);

const deleteTodo = (todo: Todo) => () => axios.delete(`http://.../${todo.id}?version=${todo.version}`);
const { load: loadDeleteTodo } = useAsync(deleteTodo(todo));

useEffect(() => loadTodo(props.id), []); // or pass [props.id] as 2nd argument

return (<button onClick={loadDeleteTodo}>Delete it</button>);
```

**What's bad about it?**
- `const ... = useAsync(deleteTodo(todo));` because `todo` is `undefined` when the component mounts. ... Initially I wanted to use `useAsync(deleteTodo(todo.id, todo.version))`, but that of course will crash, because `id of undefined`.

But (sadly) we cannot use conditionals with hooks. 

**What was good about the old nested-style Loads components?** You could do this:
```jsx
<Loads ...>
  {({response}) =>
    {response && // within here you can be 100% sure that response !== undefined
      <Loads ...> // access response.xyz safely
      </Loads>
    }
  }
</Loads>
```

Btw: I'm using TypeScript, which is a major part of the problem 🤣 It will throw an error message if you write `useAsync(deleteTodo(todo))`, because `todo` can be `undefined` here. I know, I can ignore the check by using `todo!`, but that's not nice. And I'd say: TypeScript is right: The value can be `undefined` and that's unsafe.
Though I'm looking for a way to prevent this.

I came up with 2 (unsatisfying) solution:

1. 
```
const deleteTodo = (todo: Todo | undefined) => {
  if(todo) {
    return () => axios.delete(...);
  } else {
    return undefined;
  }
}
```
I think that this is too much code for such a simple use case. And additionally the hook must handle the `undefined` now.

2. Use nested components
```
const getTodoById = (id: string) => axios.get(`http://.../${id}`);
const { response: todo, load: loadTodo } = useAsync(getTodoById);

if(!todo) {
  return null;
} else {
  return (  
    <NestedComponent todo={todo} />
  );
}
```
And then handle delete hook within the nested component, because there you can be sure that it won't be `undefined`.

**Comment by benneq** [comment]
I now figured it out! The solution is quite simple, but maybe it can be somehow made a bit more elegant.
```jsx
// api
const getTodoById = (id: string) => axios.get(`http://.../${id}`);
const deleteTodo = (id: string, version:string) => axios.delete(`http://.../${id}?version=${version}`);

// component
const cmp = (props) => {
  const { response: todo, load: loadTodo } = useAsync(getTodoById);
  const { load: loadDeleteTodo } = useAsync(deleteTodo);

  const deleteTodoFnWrapper = (id, version) => () => loadDeleteTodo(id, version);

  useEffect(() => load(props.id), []);

  if(!todo) {
    return null;
  } else {
    return (
      <>
        <button onClick={() => loadDeleteTodo(todo.id, todo.version)}>delete1</button>
        <button onClick={deleteTodoFnWrapper(todo.id, todo.version)}>delete2</button>
      </>
    )
  }
}
```

Both variants work.

It would be cool if a combination of both is possible, with:
- no arrow function in `onClick`
- and no additional wrapper function `deleteTodoFnWrapper`

**Comment by jxom** [comment]
Check out v7 :)
